version: "3"
services:
  mysql-my-app:
    image: mysql:8
    networks:
      - network-my-app
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project
  myapp:
    image: my-app-image
    ports:
      - "4040:8080"
    networks:
      - network-my-app
    depends_on:
      - mysql-my-app

networks:
  network-my-app: